[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/personnes/index.html"
to = "/equipe/"

[[redirects]]
from = "/organisations/index.html"
to = "/partenaires/"

[[redirects]]
from = "/offre/index.html"
to = "/offre-de-services/"

[[redirects]]
from = "/services/index.html"
to = "/offre-de-services/"

[[redirects]]
from = "/personnes/equipe-editoriale/index.html"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/projets/index.html"
to = "/etudes-de-cas/"

